### ISSUE TITLE
2x slower with k=18

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophasm2#12]
I've done some first a bit complex benchmark for one of my DBs for diagnostics of resistance (~661 executions of ProphAsm).

ProphAsm2 is really fast!!! 

However, I noticed that from some reason, with k=18 it's approx 2x slower compared to k=31. Is there any reason for this? With ProphAsm 1, I didn't observe this.

```
ProphAsm, k18

real	7m54.141s
user	43m45.501s
sys	1m28.739s

ProphAsm, k31

real	8m29.515s
user	48m24.024s
sys	1m25.909s


ProphAsm 2, k18

real	4m35.686s
user	21m11.361s
sys	1m44.798s


ProphAsm 2, k31

real	2m51.831s
user	11m32.846s
sys	1m25.608s
```

**Comment by PavelVesely** [comment]
> However, I noticed that from some reason, with k=18 it's approx 2x slower compared to k=31. Is there any reason for this?

Interesting. My guess is that this is because of the dBG structure (much more branching / disconnected for $k=18$). Actually what is the dataset you're running it on?

**Comment by PavelVesely** [comment]
Would be interesting to see the number of simplitigs for $k=18$ and $k=31$. Not sure what else could cause such a big difference...

**Comment by karel-brinda** [comment]
This doesn’t explain. In case of ProphAsm 1 there was no such effect.
Also,we  dont construct dbg explicitely so dbg topology should play no role.

Maybe an effect of deletions in khash? This could in theory explain that….
 (If answers for previously deleted kmers are slow)

Should be reproducible with two pneumococcal genomes, while computing
intersection and both sym diffs
