### ISSUE TITLE
Feature request: Rolling hashing

### ISSUE THREAD

**Issue by karel-brinda** [prophyle/prophasm2#5]
Not sure if this is already incorporated into KmerCamel; can be done eg via NtHash (http://dx.doi.org/10.1093/bioinformatics/btw397)

This should fix the performance issues in case of eg reading from reads

**Comment by OndrejSladky** [comment]
It seems that currently the computation of the hash takes about 3% of the total computation. I doubt that the rolling hash could be that much faster than what we're currently using as the Wang hash is just a few bit operations.

Hence I'd stick to the current hash function, as the amount of work required to modify khash to allow for rolling functions  seems to be disproportional to the unclear benefits it brings.

Feel free to reopen if you disagree.
